addons:
  sauce_connect:
    username: metal-js
    no_ssl_bump_domains: all
  jwt:
    secure: rV35O/fLO1NHiINBspiMzvWWtJPBdetUb3bB4mBB2Qrqf0WMRMGJ4Pgkaxl0p9JqAgPMQ/HSQTKLPNKaATc5g6GO46H7N1ykWBLrhsi7YSgopbNwUw95RebaZc42iyfgbnYG1hU8YEmes01UwXLsVup6qNt7X64I+M/KcfM6Cb8=

before_install:
  - nvm install 7
  - npm install -g gulp
  - npm install -g lerna@2.2.0

install:
  - npm run lerna

jdk:
  - oraclejdk8

language: java

script:
  - gulp test:saucelabs
  - npm run test:isomorphic
